package codex.ontology

import kotlinx.serialization.Serializable

/**
 * Immutable result of the ontological derivation from SQL LMD.
 *
 * Computed (not guessed) by [OntologyDeriver.derive] from the DDL/INSERT
 * script generated by `ImportBookSqlTask`. Exposes three archetypal views
 * (P1-19 spec): bounded contexts, aggregates, value objects.
 *
 * @property boundedContexts groups of tables linked by FK (connectivity).
 * @property aggregates root tables referenced via ON DELETE CASCADE and
 *           their dependent entities.
 * @property valueObjects tables without outgoing FK (no REFERENCES in their
 *           CREATE TABLE body).
 */
@Serializable
data class OntologyMapping(
    val boundedContexts: List<BoundedContext>,
    val aggregates: List<Aggregate>,
    val valueObjects: List<ValueObject>
)

/**
 * A group of tables linked by foreign-key relationships (connected
 * component of the FK graph).
 *
 * @property name human-readable label derived from the LDD title or a
 *           deterministic fallback.
 * @property tables tables belonging to this bounded context.
 */
@Serializable
data class BoundedContext(
    val name: String,
    val tables: List<String>
)

/**
 * An aggregate root and the tables that depend on it via
 * `ON DELETE CASCADE`.
 *
 * @property rootTable the table referenced by dependents through a
 *           CASCADE foreign key.
 * @property dependentTables tables whose FK targets the root with the
 *           `ON DELETE CASCADE` clause.
 */
@Serializable
data class Aggregate(
    val rootTable: String,
    val dependentTables: List<String>
)

/**
 * A table without outgoing foreign keys — a candidate value object in
 * the DDD sense (no identity-bearing relationships, immutable payload).
 *
 * @property table the table name.
 * @property columns column names declared in the CREATE TABLE body.
 */
@Serializable
data class ValueObject(
    val table: String,
    val columns: List<String>
)